### ISSUE TITLE
Food page layout

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/SlimPickins#4]
When I go to view a food record from search, I want to see the following information: Serving size, Calories per serving, Dietary restriction(i.e. not good for Nut allergies, Diabetes, High Blood Pressure, etc.), Diet preference (i.e. Keto, Paleo, Vegan, Vegetarian, etc.), and whether it's a "Favorite" food item

**Comment by mattyplo** [comment]
Perhaps in addition to, or instead of being a favorite food item, it could also have a rating between 1 and 5?  

As a user, I want to be able to rate a food item so I can see how popular it has been.
